### PR TITLE
Fix how annotations are extracted. Only those actually starting with `@` are handled

### LINKED ISSUE #684: A comment starting with the word ignore cancels the annotation @ignore
Classes marked as ignore are not ignored because of the content of the comment.
```
/**
 * @ignore
 * Ignore start this comment and causes problems
 */

```

```
/**
 * @ignore
 * This comment does not start with the word ignore causes no problems
 */
```

```
/**
 * @ignore
 * ignore
 * alone the word causes no problems 
 */
```

> atoum version: 2.8.2
=> PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
=> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
=>     with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
=>     with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.

### PR DESCRIPTION
**Pull request by jubianchi**
Closes #684

### CODE REVIEW

File: classes/annotations/extractor.php [hunk 1]
```diff
@@ -38,7 +44,7 @@ public function extract($comments)
                         }
 
                         foreach ($this->handlers as $handlerAnnotation => $handlerValue) {
-                            if ($annotation == strtolower($handlerAnnotation)) {
+                            if (ltrim($annotation, '@') == strtolower($handlerAnnotation)) {
```
Comment (jubianchi) [inline classes/annotations/extractor.php]: useless ltrim
